---
format: html
---

Ce site fournit des fiches pour les espèces protégées observées en Île-de-France.

Les données d'observations sont issues du SINP (national et régional) et seules les espèces observées au moins 3 fois ont été conservées.

Tous les statuts de protection ne sont pas pris en compte, seules les espèces dont non seulement les individus mais aussi leur habitat sont considérées ici.

## Mollusques

[Liste des mollusques protégés sur l'ensemble du territoire français métropolitain : Article 2](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000000645048)

> *I. Sont interdits sur tout le territoire métropolitain et en tout temps la destruction ou l'enlèvement des oeufs, la destruction, la mutilation, la capture ou l'enlèvement, la perturbation intentionnelle des animaux dans le milieu naturel.*
>
> *II. Sont interdites sur les parties du territoire métropolitain où l'espèce est présente ainsi que dans l'aire de déplacement naturel des noyaux de populations existants la destruction, l'altération ou la dégradation des sites de reproduction et des aires de repos des animaux. Ces interdictions s'appliquent aux éléments physiques ou biologiques réputés nécessaires à la reproduction ou au repos de l'espèce considérée, aussi longtemps qu'ils sont effectivement utilisés ou utilisables au cours des cycles successifs de reproduction ou de repos de cette espèce et pour autant que la destruction, l'altération ou la dégradation remette en cause le bon accomplissement de ces cycles biologiques.*
>
> *III. Sont interdits sur tout le territoire national et en tout temps la détention, le transport, la naturalisation, le colportage, la mise en vente, la vente ou l'achat, l'utilisation, commerciale ou non, des spécimens prélevés :*
>
> -   *dans le milieu naturel du territoire métropolitain de la France, après le 24 novembre 1992 ;*
>
> -   *dans le milieu naturel du territoire européen des autres Etats membres de l'Union européenne, après la date d'entrée en vigueur de la directive du 21 mai 1992 susvisée.*

## Ecrevisses

[Protection des écrevisses autochtones sur le territoire français métropolitain : Article 1](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000471000/)

> *Il est interdit d'altérer et de dégrader sciemment les milieux particuliers aux espèces*

## Insectes

[Arrêté du 23 avril 2007 fixant les listes des insectes protégés sur l'ensemble du territoire et les modalités de leur protection: Article 2](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000465500/2020-09-30/)

> *I. Sont interdits, sur tout le territoire métropolitain et en tout temps, la destruction ou l'enlèvement des oeufs, des larves et des nymphes, la destruction, la mutilation, la capture ou l'enlèvement, la perturbation intentionnelle des animaux dans le milieu naturel.*
>
> *II. Sont interdites, sur les parties du territoire métropolitain où l'espèce est présente ainsi que dans l'aire de déplacement naturel des noyaux de populations existants la destruction, l'altération ou la dégradation des sites de reproduction et des aires de repos des animaux. Ces interdictions s'appliquent aux éléments physiques ou biologiques réputés nécessaires à la reproduction ou au repos de l'espèce considérée, aussi longtemps qu'ils sont effectivement utilisés ou utilisables au cours des cycles successifs de reproduction ou de repos de cette espèce et pour autant que la destruction, l'altération ou la dégradation remette en cause le bon accomplissement de ces cycles biologiques.*
>
> *III. Sont interdits, sur tout le territoire national et en tout temps, la détention, le transport, la naturalisation, le colportage, la mise en vente, la vente ou l'achat, l'utilisation commerciale ou non, des spécimens prélevés :*
>
> -   *dans le milieu naturel du territoire métropolitain de la France, après le 24 septembre 1993 ;*
> -   *dans le milieu naturel du territoire européen des autres Etats membres de l'Union européenne, après la date d'entrée en vigueur de la directive du 21 mai 1992 susvisée.*

## Poissons

[Arrêté du 08/12/88 fixant la liste des espèces de poissons protégées sur l'ensemble du territoire national: Article 1](https://aida.ineris.fr/reglementation/arrete-081288-fixant-liste-especes-poissons-protegees-lensemble-territoire-national)

> *Sont interdits en tout temps, sur tout le territoire national :*
>
> *I. La destruction ou l'enlèvement des oeufs ;*
>
> *II. La destruction, l'altération ou la dégradation des milieux particuliers, et notamment des lieux de reproduction, désignés par arrêté préfectoral*

## Amphibiens et reptiles

[Arrêté du 8 janvier 2021 fixant la liste des amphibiens et des reptiles représentés sur le territoire métropolitain protégés sur l'ensemble du territoire national et les modalités de leur protection : Article 2](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000043113964)

> *I. Sont interdits, sur tout le territoire métropolitain et en tout temps : - la destruction ou l'enlèvement des œufs et des nids, la destruction, la mutilation, la capture ou l'enlèvement des animaux ; - la perturbation intentionnelle des animaux, pour autant que la perturbation remette en cause le bon accomplissement des cycles biologiques de l'espèce considérée.*
>
> *II. Sont interdites sur les parties du territoire métropolitain où l'espèce est présente ainsi que dans l'aire de déplacement naturel des noyaux de populations existants, la destruction, l'altération ou la dégradation des sites de reproduction et des aires de repos des animaux. Ces interdictions s'appliquent aux éléments physiques ou biologiques réputés nécessaires à la reproduction ou au repos de l'espèce considérée, aussi longtemps qu'ils sont effectivement utilisés ou utilisables au cours des cycles successifs de reproduction ou de repos de cette espèce et pour autant que la destruction, l'altération ou la dégradation remette en cause le bon accomplissement de ces cycles biologiques.*
>
> *III. Sont interdits, sur tout le territoire national et en tout temps, la détention, le transport, la naturalisation, le colportage, la mise en vente, la vente ou l'achat, l'utilisation, commerciale ou non, des spécimens prélevés :*
>
> -   *dans le milieu naturel du territoire métropolitain de la France, après le 12 mai 1979 ;*
>
> -   *dans le milieu naturel du territoire européen des autres Etats membres de l'Union européenne, après la date d'entrée en vigueur de la directive du 21 mai 1992 susvisée.*

## Oiseaux

[Liste des oiseaux protégés sur l'ensemble du territoire et les modalités de leur protection : Article 3](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000021384277/2015-07-29)

> I. Sont interdits sur tout le territoire métropolitain et en tout temps :
>
> -   la destruction intentionnelle ou l'enlèvement des œufs et des nids ;
>
> -   la destruction, la mutilation intentionnelles, la capture ou l'enlèvement des oiseaux dans le milieu naturel ;
>
> -   la perturbation intentionnelle des oiseaux, notamment pendant la période de reproduction et de dépendance, pour autant que la perturbation remette en cause le bon accomplissement des cycles biologiques de l'espèce considérée.
>
> II\. Sont interdites sur les parties du territoire métropolitain où l'espèce est présente ainsi que dans l'aire de déplacement naturel des noyaux de populations existants la destruction, l'altération ou la dégradation des sites de reproduction et des aires de repos des animaux. Ces interdictions s'appliquent aux éléments physiques ou biologiques réputés nécessaires à la reproduction ou au repos de l'espèce considérée, aussi longtemps qu'ils sont effectivement utilisés ou utilisables au cours des cycles successifs de reproduction ou de repos de cette espèce et pour autant que la destruction, l'altération ou la dégradation remette en cause le bon accomplissement de ces cycles biologiques.
>
> III\. Sont interdits sur tout le territoire national et en tout temps la détention, le transport, la naturalisation, le colportage, la mise en vente, la vente ou l'achat, l'utilisation commerciale ou non des spécimens d'oiseaux prélevés :
>
> -   dans le milieu naturel du territoire métropolitain de la France, après la date d'entrée en vigueur de l'interdiction de capture ou d'enlèvement concernant l'espèce à laquelle ils appartiennent ;
>
> -   dans le milieu naturel du territoire européen des autres Etats membres de l'Union européenne, après la date d'entrée en vigueur dans ces Etats de la directive du 2 avril 1979 susvisée.

## Mammifères

[Liste des mammifères terrestres protégés sur l'ensemble du territoire français et les modalités de leur protection : Article 2](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000649682)

> I. Sont interdits sur tout le territoire métropolitain et en tout temps la destruction, la mutilation, la capture ou l'enlèvement, la perturbation intentionnelle des animaux dans le milieu naturel.
>
 II\. Sont interdites sur les parties du territoire métropolitain où l'espèce est présente, ainsi que dans l'aire de déplacement naturel des noyaux de populations existants, la destruction, l'altération ou la dégradation des sites de reproduction et des aires de repos des animaux. Ces interdictions s'appliquent aux éléments physiques ou biologiques réputés nécessaires à la reproduction ou au repos de l'espèce considérée, aussi longtemps qu'ils sont effectivement utilisés ou utilisables au cours des cycles successifs de reproduction ou de repos de cette espèce et pour autant que la destruction, l'altération ou la dégradation remette en cause le bon accomplissement de ces cycles biologiques.
