name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Quarto
      run: |
        wget https://quarto.org/download/latest/quarto-linux-amd64.deb
        sudo dpkg -i quarto-linux-amd64.deb

    - name: Render site
      run: |
        quarto render

    - name: Set correct permissions for the site directory
      run: sudo chmod -R 755 _site

    - name: Move site to docs
      run: |
        rm -rf docs/*
        mv fiches/_site/* docs/

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git add docs
        git commit -m "Update site"
        git push origin -f

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.3
      with:
        branch: gh-pages
        folder: docs
