name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set correct permissions for the site directory
      run: sudo chmod -R 755 docs

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git add docs
        git commit -m "Update site"
        git push origin -f

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.3
      with:
        branch: gh-pages
        folder: docs
